//
//  HomeInteractor.swift
//  CleanSwiftDemo1
//
//  Created by Purplle on 15/02/22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
  func doSomething(request: Home.User.Request)
}

protocol HomeDataStore {
    var users: [UserModel1]? { get }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var users: [UserModel1]?
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    
    // MARK: Do something
    func doSomething(request: Home.User.Request) {
        
        worker = HomeWorker()
        worker?.getUserList(completionHandler: { [weak self] success, users in
            guard let self = self else { return }
            self.users = users
            let response = Home.User.Response(data: users)
            self.presenter?.presentSomething(response: response)
        })
    }
}
