//
//  HomeWorker.swift
//  CleanSwiftDemo1
//
//  Created by Purplle on 15/02/22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    
    typealias SuccessHandler = (_ success:Bool,_ users: [UserModel])->Void

    func getUserList(completionHandler: @escaping SuccessHandler) {
        
        ServiceUtility.callWebServiceWithLink("https://gorest.co.in/public/v2/users", parameters: NSMutableDictionary()) { success, resp in
            do {
                var users = [UserModel]()
                for user in resp {
                    let jsonDecoder = JSONDecoder()
                    let userData = try JSONSerialization.data(withJSONObject: user, options: .prettyPrinted)
                    let user = try jsonDecoder.decode(UserModel.self, from: userData)
                    users.append(user)
                    
                }
                completionHandler(success,users)
            } catch {
                completionHandler(false,[UserModel]())
                print("Eroor")
            }
        }
    }
}
