//
//  HomeModels.swift
//  CleanSwiftDemo1
//
//  Created by Purplle on 15/02/22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

struct Home: Codable {
    
    
    // MARK: Use cases
    struct User: Codable {
                
        struct Request
        {
        }
        struct Response: Codable
        {
            let data: [UserModel1]?
        }
        struct ViewModel: Codable
        {
            var userList: [UserModel1]
        }
    }
}

extension Home: APIWrapperModelType, APIService {
    
    typealias APICodable = Home.User.Response
    static var httpMethod: HTTPMethod = .post
    static var url: String = ""
    
}
