//
//  LoginWorker.swift
//  CleanSwiftDemo1
//
//  Created by zeba on 26/11/19.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
    typealias SuccessHandler = (_ success:Bool)->Void
    
    /// Call login API
    func login(email: String, password: String, completionHandler: @escaping SuccessHandler)
    {
        ServiceUtility.callWebServiceWithLink("https://restful-booker.herokuapp.com/auth", params: ["username" : email,"password" : password], completionHandler: { (success,resp) -> Void in
            completionHandler(success)
        })
    }
}
