//
//  LoginModels.swift
//  CleanSwiftDemo1
//
//  Created by zeba on 26/11/19.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

struct Login: Codable {
    
    // MARK: - Use cases
    struct LoginInfo {
        var userName : String
        var password : String
    }
    
    struct User: Codable {
        
        struct Request {
            var loginInfo : LoginInfo
        }
        
        struct Response: Codable {
            var loginResp: LoginResponse?
            var succes : Bool?
            var message: String?
        }
        
        struct ViewModel: Codable {
            var isSuccess : Bool
            var message: String?
        }
    }
}
extension Login: APIWrapperModelType, APIService {
    
    typealias APICodable = LoginResponse
    static var httpMethod: HTTPMethod = .post
    static var url: String = ""
    static var params: [String: Any] = [:]
}

struct LoginResponse: Codable {
    
    var token: String?
    var reason: String?
}
